### PR TITLE
Updated for Pymongo 3.0

### LINKED ISSUE #6: mod-mongodb is broken with new pymongo module.
```from pymongo.connection import Connection``` does not work anymore.

shinken arbiter output:
```

1428945428] ERROR: [Shinken] The module mongodb raised an exception Cannot find the module python-pymongo. Please install it., I remove it! traceback=Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/shinken/modulesmanager.py", line 174, in get_instances
    inst = module.get_instance(mod_conf)
  File "/usr/share/pyshared/shinken/modules/mod-mongodb/module.py", line 63, in get_instance
    raise Exception('Cannot find the module python-pymongo. Please install it.')
Exception: Cannot find the module python-pymongo. Please install it.

```

python interpreter output:
```
>>> from pymongo.connection import Connection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named connection
>>> 
```

See the [pymongo docs](https://api.mongodb.org/python/current/tutorial.html) to see examples on how to create a connection.

### PR DESCRIPTION
**Pull request by aviau**
Closes #6

not fully tested yet. Give me a few mins.

### CODE REVIEW

**Comment by naparuba** [comment]
works with pymongo 2? Maybe a try/except with both case?

**Comment by ReAzem** [comment]
I don't know since how long, but even pymongo 2 recommended using ``MongoClient`` instead of ``pymongo.connection``.

I tried with pymongo 2.8 and it worked.

**Comment by naparuba** [comment]
Oki, I got some centos 6 available, I can give a test ^^

**Comment by ReAzem** [comment]
@naparuba Have you tested?

**Pull request merged**
